
project_id = "bblpiatmtnlhnbavhkau"

[functions.is-admin]
verify_jwt = true

[functions.get-user-info]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.send-password-reset-email]
verify_jwt = true

[functions.send-mission-notification]
verify_jwt = true

[functions.terminology-search]
verify_jwt = false

