
export const LANGUAGES = [
  // All languages in one sorted array
  "Afrikaans", "Albanais", "Allemand (Allemagne)", "Allemand (Autriche)", "Allemand (Suisse)", 
  "American Sign Language (ASL)", "Amharique", "Anglais (Afrique du Sud)", "Anglais (Australie)", 
  "Anglais (Ghana)", "Anglais (Inde)", "Anglais (Irlande)", "Anglais (Kenya)", "Anglais (Nigeria)", 
  "Anglais (Nouvelle-Zélande)", "Anglais (Écosse)", "Anglais (UK)", "Anglais (US)", "Apache",
  "Arabe (Algérien)", "Arabe (Bahreïni)", "Arabe (Égyptien)", "Arabe (Émirati)", "Arabe (Irakien)", 
  "Arabe (Jordanien)", "Arabe (Koweïtien)", "Arabe (Libanais)", "Arabe (Libyen)", "Arabe (Mauritanien)", 
  "Arabe (Omanais)", "Arabe (Palestinien)", "Arabe (Qatari)", "Arabe (Saoudien)", "Arabe (Soudanais)", 
  "Arabe (Standard)", "Arabe (Syrien)", "Arabe (Tchadien)", "Arabe (Tunisien)", "Arabe (Yéménite)",
  "Arménien", "Aymara", "Azéri", "Bambara", "Baoulé", "Bengali", "Berbère (Chaoui)", "Berbère (Chleuh)", 
  "Berbère (Kabyle)", "Berbère (Mozabite)", "Berbère (Rifain)", "Berbère (Touareg)", "Bhojpuri", "Birman",
  "British Sign Language (BSL)", "Bulgare", "Bété", "Cantonais", "Cebuano", "Chamorro", "Cherokee", 
  "Cinghalais", "Coréen", "Croate", "Créole Cap-Verdien", "Créole Guadeloupéen", "Créole Guyanais", 
  "Créole Haïtien", "Créole Jamaïcain", "Créole Louisianais", "Créole Martiniquais", "Créole Mauricien", 
  "Créole Réunionnais", "Créole Seychellois", "Danois", "Dari (Afghanistan)", "Deutsche Gebärdensprache (DGS)", 
  "Diakhanké", "Dioula", "Estonien", "Espagnol (Argentine)", "Espagnol (Chili)", "Espagnol (Colombie)", 
  "Espagnol (Espagne)", "Espagnol (Mexique)", "Espagnol (Pérou)", "Fidjien", "Finnois", "Fon", "Four", 
  "Français", "Géorgien", "Grec", "Guarani", "Gujarati", "Hakka", "Hassaniya", "Haoussa", "Hawaiien", 
  "Hindi", "Hongrois", "Igbo", "Ilokano", "Indonésien", "International Sign", "Inuktitut", "Islandais", 
  "Italien", "Japonais", "Javanais", "Kannada", "Kashmiri", "Kazakh", "Khmer", "Kikongo", "Kinyarwanda", 
  "Kirghize", "Kirundi", "Konkani", "Kurde (Kurmandji)", "Kurde (Sorani)", "Langue des Signes Française (LSF)", 
  "Langue des Signes Québécoise (LSQ)", "Lao", "Letton", "Lingala", "Lituanien", "Macédonien", "Maithili", 
  "Malais", "Malayalam", "Malinké", "Mandarin", "Marathi", "Marshallais", "Maya (K'iche')", "Maya (Yucatèque)", 
  "Maori", "Min Nan", "Mina", "Mongol", "Moore", "Nahuatl", "Navajo", "Ndébélé", "Néerlandais", "Népalais", 
  "Norvégien", "Oromo", "Ouïghour", "Ourdou", "Ouzbek", "Pachto", "Papiamento", "Persan (Iran)", "Peul", 
  "Polonais", "Portugais (Brésil)", "Portugais (Portugal)", "Punjabi (Inde)", "Punjabi (Pakistan)", "Quechua", 
  "Roumain", "Russe", "Samoan", "Santali", "Serbe", "Shona", "Sindhi", "Slovaque", "Somali", "Soninké", 
  "Soussou", "Sundanais", "Suédois", "Swahili", "Sérère", "Tadjik", "Tagalog", "Tahitien", "Tamoul (Inde)", 
  "Tamoul (Sri Lanka)", "Tamasheq", "Tchèque", "Teochew", "Thaï", "Tibétain", "Tigrigna", "Tongan", 
  "Tshiluba", "Tswana", "Turkmène", "Télougou", "Ukrainien", "Vietnamien", "Wolof", "Wu (Shanghaïen)", 
  "Xhosa", "Yoruba", "Zaghawa", "Zoulou", "Éwé"
].sort();
