
[[headers]]
  for = "/*"
  [headers.values]
    Service-Worker-Allowed = "/"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' cdn.onesignal.com onesignal.com *.onesignal.com https://*.supabase.co wss://*.supabase.co; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://bblpiatmtnlhnbavhkau.supabase.co https://*.onesignal.com https://fonts.googleapis.com https://fonts.gstatic.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' cdn.onesignal.com onesignal.com *.onesignal.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: blob: https:; media-src 'self' https:; worker-src 'self' blob: cdn.onesignal.com; frame-src 'self' onesignal.com *.onesignal.com; child-src 'self' blob: onesignal.com *.onesignal.com; manifest-src 'self' onesignal.com *.onesignal.com;"

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["web-push"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

