// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bblpiatmtnlhnbavhkau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJibHBpYXRtdG5saG5iYXZoa2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNDU3ODMsImV4cCI6MjA1MzcyMTc4M30.hHQUzahxDt3917D0MSrG7mHh8CoiCVlDyc-2FHPfM_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);